services:
  hummingbot:
    container_name: hummingbot
    image: hummingbot/hummingbot:latest
    # build: # Uncomment this build section and comment image to build Hummingbot locally
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    # Auto-start (enable after initial setup):
    # environment:
    #   - CONFIG_PASSWORD=a
    #   - CONFIG_FILE_NAME=dollar_a_day_pmm.py
    #   - SCRIPT_CONFIG=conf_dollar_a_day_pmm.yml

  # gateway:
  #  restart: always
  #  container_name: gateway
  #  image: hummingbot/gateway:latest
  #  ports:
  #    - "15888:15888"
  #  volumes:
  #    - "./gateway-files/conf:/home/gateway/conf"
  #    - "./gateway-files/logs:/home/gateway/logs"
  #    - "./certs:/home/gateway/certs"
  #  environment:
  #    - GATEWAY_PASSPHRASE=admin
  #    - DEV=true
